In [12]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

In [13]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[43, 53, 78,  4],
       [29, 27, 98, 28],
       [12, 15,  4, 14],
       [70, 96, 37, 69],
       [42, 56, 38, 33],
       [ 2,  9, 44, 45]])

In [14]:
np.sort(a)[::-1]

array([91, 90, 89, 54, 52, 52, 46, 42, 31, 28, 21, 15, 13, 13,  2])

In [15]:
np.sort(b,axis=0)

array([[ 2,  9,  4,  4],
       [12, 15, 37, 14],
       [29, 27, 38, 28],
       [42, 53, 44, 33],
       [43, 56, 78, 45],
       [70, 96, 98, 69]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [16]:
# code
np.append(a,200)

array([ 21,  52,  28,   2,  46,  42,  52,  91,  13,  15,  89,  13,  31,
        54,  90, 200])

In [17]:
b

array([[43, 53, 78,  4],
       [29, 27, 98, 28],
       [12, 15,  4, 14],
       [70, 96, 37, 69],
       [42, 56, 38, 33],
       [ 2,  9, 44, 45]])

In [18]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[43.        , 53.        , 78.        ,  4.        ,  0.73866635],
       [29.        , 27.        , 98.        , 28.        ,  0.66542992],
       [12.        , 15.        ,  4.        , 14.        ,  0.9043458 ],
       [70.        , 96.        , 37.        , 69.        ,  0.38237223],
       [42.        , 56.        , 38.        , 33.        ,  0.86561377],
       [ 2.        ,  9.        , 44.        , 45.        ,  0.63492514]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [19]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [20]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [22]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [23]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [24]:
# code
a.shape

(15,)

In [25]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [26]:
np.expand_dims(a,axis=1)

array([[21],
       [52],
       [28],
       [ 2],
       [46],
       [42],
       [52],
       [91],
       [13],
       [15],
       [89],
       [13],
       [31],
       [54],
       [90]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [27]:
a

array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

In [28]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 13, 14]),)

In [29]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([21,  0, 28,  2, 46, 42,  0,  0, 13, 15,  0, 13, 31,  0,  0])

In [30]:
np.where(a%2 == 0,0,a)

array([21,  0,  0,  0,  0,  0,  0, 91, 13, 15, 89, 13, 31,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [31]:
# code
a

array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

In [32]:
np.argmax(a)

7

In [33]:
b

array([[43, 53, 78,  4],
       [29, 27, 98, 28],
       [12, 15,  4, 14],
       [70, 96, 37, 69],
       [42, 56, 38, 33],
       [ 2,  9, 44, 45]])

In [34]:
np.argmax(b,axis=0)

array([3, 3, 1, 3])

In [35]:
np.argmax(b,axis=1)

array([2, 2, 1, 1, 1, 3])

In [36]:
# np.argmin
np.argmin(a)

3

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [37]:
a

array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

In [38]:
np.cumsum(a)

array([ 21,  73, 101, 103, 149, 191, 243, 334, 347, 362, 451, 464, 495,
       549, 639])

In [39]:
b

array([[43, 53, 78,  4],
       [29, 27, 98, 28],
       [12, 15,  4, 14],
       [70, 96, 37, 69],
       [42, 56, 38, 33],
       [ 2,  9, 44, 45]])

In [40]:
np.cumsum(b,axis=1)

array([[ 43,  96, 174, 178],
       [ 29,  56, 154, 182],
       [ 12,  27,  31,  45],
       [ 70, 166, 203, 272],
       [ 42,  98, 136, 169],
       [  2,  11,  55, 100]])

In [41]:
np.cumsum(b)

array([ 43,  96, 174, 178, 207, 234, 332, 360, 372, 387, 391, 405, 475,
       571, 608, 677, 719, 775, 813, 846, 848, 857, 901, 946])

In [42]:
# np.cumprod
np.cumprod(a)

array([                 21,                1092,               30576,
                     61152,             2812992,           118145664,
                6143574528,        559065282048,       7267848666624,
           109017729999360,    9702577969943040,  126133513609259520,
       3910138921887045120, 8233316971095368704, 3128764450201118720])

In [43]:
a

array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [44]:
a

array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

In [45]:
np.percentile(a,50)

42.0

In [46]:
np.median(a)

42.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [47]:
# code
a

array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

In [48]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [49]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [50]:
# code
a


array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

In [51]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([90])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [52]:
# code
a

array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

In [53]:
np.flip(a)

array([90, 54, 31, 13, 89, 15, 13, 91, 52, 42, 46,  2, 28, 52, 21])

In [54]:
b

array([[43, 53, 78,  4],
       [29, 27, 98, 28],
       [12, 15,  4, 14],
       [70, 96, 37, 69],
       [42, 56, 38, 33],
       [ 2,  9, 44, 45]])

In [55]:
np.flip(b,axis=1)

array([[ 4, 78, 53, 43],
       [28, 98, 27, 29],
       [14,  4, 15, 12],
       [69, 37, 96, 70],
       [33, 38, 56, 42],
       [45, 44,  9,  2]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [56]:
# code
a

array([21, 52, 28,  2, 46, 42, 52, 91, 13, 15, 89, 13, 31, 54, 90])

In [57]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [58]:
# code
a

array([110, 530,  28,   2,  46,  42,  52,  91,  13,  15,  89,  13,  31,
        54,  90])

In [59]:
np.delete(a,[0,2,4])

array([530,   2,  42,  52,  91,  13,  15,  89,  13,  31,  54,  90])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [60]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [61]:
np.intersect1d(m,n)

array([3, 4, 5])

In [62]:
np.setdiff1d(n,m)

array([6, 7])

In [63]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [64]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [65]:
# code
a

array([110, 530,  28,   2,  46,  42,  52,  91,  13,  15,  89,  13,  31,
        54,  90])

In [66]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 25, 46, 42, 52, 75, 25, 25, 75, 25, 31, 54, 75])

In [67]:
# 17. np.swapaxes

In [68]:
# 18. np.uniform

In [69]:
# 19. np.count_nonzero

In [70]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [71]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [72]:

# 25. np.allclose and equals