### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
d=np.array([[1,2,3],
           [4,5,6]])
print(d)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(10) #1*10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [6]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [11]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# np.random
np.random.random((3,4))

array([[0.71447728, 0.34767881, 0.26728905, 0.33690482],
       [0.70113105, 0.72925181, 0.62838426, 0.86519384],
       [0.46620002, 0.45037159, 0.97767659, 0.62361136]])

In [54]:
np.linspace(-10,10,7)

array([-10.        ,  -6.66666667,  -3.33333333,   0.        ,
         3.33333333,   6.66666667,  10.        ])

In [15]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [16]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
# ndim
a3.ndim

3

In [57]:
# shape
print(a3.shape)


(2, 2, 2)


In [62]:
# size
print(a2.size)
print(a2.itemsize)
a2

12
8


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
# itemsize
a3.itemsize

8

In [59]:
a2.itemsize

8

In [21]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [63]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [25]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [26]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [29]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 5., 17., 48.],
       [91., 34., 38.],
       [37., 81., 71.]])

In [30]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 16835.,  46818., 129504.])

In [31]:
# mean/median/std/var
np.var(a1,axis=1)

array([328.22222222, 674.88888889, 354.66666667])

In [32]:
# trigonomoetric functions
np.sin(a1)

array([[-0.95892427, -0.96139749, -0.76825466],
       [ 0.10598751,  0.52908269,  0.29636858],
       [-0.64353813, -0.62988799,  0.95105465]])

In [33]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [34]:
# log and exponents
np.exp(a1)

array([[1.48413159e+02, 2.41549528e+07, 7.01673591e+20],
       [3.31740010e+39, 5.83461743e+14, 3.18559318e+16],
       [1.17191424e+16, 1.50609731e+35, 6.83767123e+30]])

In [35]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[91., 44., 84.],
       [36., 48., 88.]])

### Indexing and Slicing

In [37]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a1[0]

0

In [66]:
a1[1]

1

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
print(a2[:][2])
print(a2[:2])

[ 8  9 10 11]
[[0 1 2 3]
 [4 5 6 7]]


In [41]:
a2[1,0] # 1 = row number 0 = column number

4

In [69]:
a2[0,1]

1

In [42]:
#  fetch 10
a2[2,2]

10

In [70]:
a2[2][2]

10

In [77]:
arr=np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
arr[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1] # 1 = number of 2d , 0 = number of row , 1=no of column

5

In [43]:
a3[1,1,0]

6

In [44]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a1[2:5]

array([2, 3, 4])

In [48]:
a1[2:5:2] #

array([2, 4])

In [46]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2[0:1]

array([[0, 1, 2, 3]])

In [52]:
a2[0,:]

array([0, 1, 2, 3])

In [53]:
a2[:,2]

array([ 2,  6, 10])

In [79]:
a2[0:2,1::2] #

array([[1, 3],
       [5, 7]])

In [80]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [81]:
a2[1,::3]

array([4, 7])

In [82]:
a2[0,:]

array([0, 1, 2, 3])

In [83]:
a2[:,2]

array([ 2,  6, 10])

In [84]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [85]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [86]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [87]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [88]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [89]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [90]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [92]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [93]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [94]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [95]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [96]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [97]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,5)

ValueError: ignored

In [ ]:
# vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,2)

ValueError: ignored