### Advanced Indexing

In [2]:
# Normal Indexing and slicing
import numpy as np
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [3]:
a[1,2]

6

In [4]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [5]:
# fancy indexing
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
# fetch 1st row 3rd row 4th row
a=np.arange(12).reshape(2,6)
print(a)
print(a[[0,1]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [15]:
# Fancy Indexing

a[:,[0,2,4]]

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [16]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[82, 93, 50, 43],
       [38, 53, 17, 27],
       [64, 51, 29,  4],
       [12, 30, 78,  3],
       [79, 50, 30,  8],
       [98, 57, 47, 86]])

In [17]:
# find all numbers greater than 50
a[a > 50]

array([82, 93, 53, 64, 51, 78, 79, 98, 57, 86])

In [18]:
# find out even numbers
a[a % 2 == 0]

array([82, 50, 38, 64,  4, 12, 30, 78, 50, 30,  8, 98, 86])

In [19]:
# find all numbers greater than 50 and are even

a[(a > 50) & (a % 2 == 0)]

array([82, 64, 78, 98, 86])

In [20]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([82, 93, 50, 43, 38, 53, 17, 27, 64, 51, 29,  4, 12, 30, 78,  3, 79,
       50, 30,  8, 57, 47, 86])

In [21]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [22]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [27]:
a=np.arange(3).reshape(1,3)
print(a)
b=np.array([5])
print(b)
print(a+b)

[[0 1 2]]
[5]
[[5 6 7]]


In [30]:
a=np.ones((3,3),dtype=int)
print(a)
b=np.array([0,1,2])
print(b)
print(a+b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0 1 2]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [33]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [34]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [35]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


### Working with mathematical formulas

In [ ]:
a = np.arange(10)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### Working with missing values

In [38]:
# Working with missing values -> np.nan
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [39]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])